name: conditional-workflow
on: [push]
jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    steps:
      - name: print the repo name
        run: echo $github.repository
  hello-world:
    if: github.repository == 'MartinGarzaFCFM/Github-Examples'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        run:  echo "Hello World!"
  goodbye-moon:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye Moon"
        run:  echo "Goodbye Moon!"