name: scheduled job
on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  hello_world:
    runs_on: ubuntu-latest
    steps:
      - name: Echo Tiempo
        run: echo "Ahora mismo el tiempo ${date}"