name: "Webhook Event Example"
on:
  repository_dispatch:
    types:
      CheckThisOut

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutRepo
        uses: actions/checkout@v4
      - name: Run a Script
        run: 'echo "Event Type: $GITHUB_EVENT_NAME"'
        
